
#region License

// Copyright (c) 2013, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This file is part of the ClearCanvas RIS/PACS open source project.
//
// The ClearCanvas RIS/PACS open source project is free software: you can
// redistribute it and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The ClearCanvas RIS/PACS open source project is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// the ClearCanvas RIS/PACS open source project.  If not, see
// <http://www.gnu.org/licenses/>.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macro.ImageViewer.Utilities.Print.Dicom {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Macro.ImageViewer.Utilities.Print.Dicom.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AE Title 的本地化字符串。
        /// </summary>
        internal static string ColumnAETitle {
            get {
                return ResourceManager.GetString("ColumnAETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        internal static string ColumnColor {
            get {
                return ResourceManager.GetString("ColumnColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string ColumnDefault {
            get {
                return ResourceManager.GetString("ColumnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 的本地化字符串。
        /// </summary>
        internal static string ColumnHost {
            get {
                return ResourceManager.GetString("ColumnHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string ColumnPort {
            get {
                return ResourceManager.GetString("ColumnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintPreviewPan 的本地化字符串。
        /// </summary>
        internal static string CommandPan {
            get {
                return ResourceManager.GetString("CommandPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintPreviewCopy 的本地化字符串。
        /// </summary>
        internal static string CommandPrintPreviewCopy {
            get {
                return ResourceManager.GetString("CommandPrintPreviewCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintPreviewCut 的本地化字符串。
        /// </summary>
        internal static string CommandPrintPreviewCut {
            get {
                return ResourceManager.GetString("CommandPrintPreviewCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintPreviewDeleteImage 的本地化字符串。
        /// </summary>
        internal static string CommandPrintPreviewDeleteImage {
            get {
                return ResourceManager.GetString("CommandPrintPreviewDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintPreviewPaste 的本地化字符串。
        /// </summary>
        internal static string CommandPrintPreviewPaste {
            get {
                return ResourceManager.GetString("CommandPrintPreviewPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintPreviewStack 的本地化字符串。
        /// </summary>
        internal static string CommandStack {
            get {
                return ResourceManager.GetString("CommandStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 的本地化字符串。
        /// </summary>
        internal static string DicomConfiguration {
            get {
                return ResourceManager.GetString("DicomConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Pixel format is not supported. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPixelFormatNotSupported {
            get {
                return ResourceManager.GetString("ExceptionPixelFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        internal static string LabelFilmSizeAutoSelect {
            get {
                return ResourceManager.GetString("LabelFilmSizeAutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排版全部图像 的本地化字符串。
        /// </summary>
        internal static string MenuCopyAllToPrintPreview {
            get {
                return ResourceManager.GetString("MenuCopyAllToPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排版序列图像 的本地化字符串。
        /// </summary>
        internal static string MenuCopyDisplaySetToPrintPreview {
            get {
                return ResourceManager.GetString("MenuCopyDisplaySetToPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排版单张图像 的本地化字符串。
        /// </summary>
        internal static string MenuCopyImageToPrintPreview {
            get {
                return ResourceManager.GetString("MenuCopyImageToPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM &amp;打印 的本地化字符串。
        /// </summary>
        internal static string MenuDicomPrint {
            get {
                return ResourceManager.GetString("MenuDicomPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印排版 的本地化字符串。
        /// </summary>
        internal static string MenuDicomPrintPreview {
            get {
                return ResourceManager.GetString("MenuDicomPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;移动 的本地化字符串。
        /// </summary>
        internal static string MenuPan {
            get {
                return ResourceManager.GetString("MenuPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除图像 的本地化字符串。
        /// </summary>
        internal static string MenuPrintPreviewDeleteImage {
            get {
                return ResourceManager.GetString("MenuPrintPreviewDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;序列打印 的本地化字符串。
        /// </summary>
        internal static string MenuSelectedDisplaySet {
            get {
                return ResourceManager.GetString("MenuSelectedDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;单张打印 的本地化字符串。
        /// </summary>
        internal static string MenuSelectedImage {
            get {
                return ResourceManager.GetString("MenuSelectedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more images do not contain pixel spacing information.  True size printing is not possible. 的本地化字符串。
        /// </summary>
        internal static string MessageCannotPrintTrueSize {
            get {
                return ResourceManager.GetString("MessageCannotPrintTrueSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected printer? 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmDeleteDicomPrinter {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteDicomPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A DICOM printer with the name &apos;{0}&apos; already exists.  Please enter a different name. 的本地化字符串。
        /// </summary>
        internal static string MessageDicomPrinterNameNotUnique {
            get {
                return ResourceManager.GetString("MessageDicomPrinterNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no DICOM printers configured.  Printers can be configured through the Tools &gt; Options &gt; DICOM &gt; Printers page. 的本地化字符串。
        /// </summary>
        internal static string MessageNoPrintersConfigured {
            get {
                return ResourceManager.GetString("MessageNoPrintersConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to establish connection with {0}.  Please check the printer configuration. 的本地化字符串。
        /// </summary>
        internal static string MessagePrinterNotConnected {
            get {
                return ResourceManager.GetString("MessagePrinterNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printing cancelled. 的本地化字符串。
        /// </summary>
        internal static string MessagePrintingCancelled {
            get {
                return ResourceManager.GetString("MessagePrintingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelling print request... 的本地化字符串。
        /// </summary>
        internal static string MessagePrintingCancelling {
            get {
                return ResourceManager.GetString("MessagePrintingCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All the images have been successfully sent to the printer. 的本地化字符串。
        /// </summary>
        internal static string MessagePrintingCompleted {
            get {
                return ResourceManager.GetString("MessagePrintingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error sending images to {0}.  Some of the films may have already been printed. 的本地化字符串。
        /// </summary>
        internal static string MessagePrintingError {
            get {
                return ResourceManager.GetString("MessagePrintingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple patients have been selected. 的本地化字符串。
        /// </summary>
        internal static string MessagePrintingMultiplePatients {
            get {
                return ResourceManager.GetString("MessagePrintingMultiplePatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending {0} of {1} image(s) to {2}... 的本地化字符串。
        /// </summary>
        internal static string MessagePrintingProgress {
            get {
                return ResourceManager.GetString("MessagePrintingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing to send {0} image(s) to {1}... 的本地化字符串。
        /// </summary>
        internal static string MessagePrintingStarting {
            get {
                return ResourceManager.GetString("MessagePrintingStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is already a print session in progress.  Please wait for the print session to finish and try again later. 的本地化字符串。
        /// </summary>
        internal static string MessagePrintSessionInProgress {
            get {
                return ResourceManager.GetString("MessagePrintSessionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is a print session in progress.  Are you sure you want to close the application? 的本地化字符串。
        /// </summary>
        internal static string MessagePrintSessionInProgressConfirmExitApplication {
            get {
                return ResourceManager.GetString("MessagePrintSessionInProgressConfirmExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown failure.  The association might have timed-out.  Check the log for more detail. 的本地化字符串。
        /// </summary>
        internal static string MessageUnknownFailure {
            get {
                return ResourceManager.GetString("MessageUnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification failed 的本地化字符串。
        /// </summary>
        internal static string MessageVerificationFailed {
            get {
                return ResourceManager.GetString("MessageVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification successful 的本地化字符串。
        /// </summary>
        internal static string MessageVerificationSuccessful {
            get {
                return ResourceManager.GetString("MessageVerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printers 的本地化字符串。
        /// </summary>
        internal static string PrintersConfiguration {
            get {
                return ResourceManager.GetString("PrintersConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加打印机 的本地化字符串。
        /// </summary>
        internal static string TitleAddPrinter {
            get {
                return ResourceManager.GetString("TitleAddPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级选项 的本地化字符串。
        /// </summary>
        internal static string TitleAdvancedOptions {
            get {
                return ResourceManager.GetString("TitleAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Print 的本地化字符串。
        /// </summary>
        internal static string TitleDicomPrint {
            get {
                return ResourceManager.GetString("TitleDicomPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Print Progress 的本地化字符串。
        /// </summary>
        internal static string TitleDicomPrintProgress {
            get {
                return ResourceManager.GetString("TitleDicomPrintProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑打印机 的本地化字符串。
        /// </summary>
        internal static string TitleEditPrinter {
            get {
                return ResourceManager.GetString("TitleEditPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试联机 的本地化字符串。
        /// </summary>
        internal static string TitleVerify {
            get {
                return ResourceManager.GetString("TitleVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Print 的本地化字符串。
        /// </summary>
        internal static string ToolbarDicomPrint {
            get {
                return ResourceManager.GetString("ToolbarDicomPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印排版 的本地化字符串。
        /// </summary>
        internal static string ToolbarDicomPrintPreview {
            get {
                return ResourceManager.GetString("ToolbarDicomPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        internal static string ToolbarPan {
            get {
                return ResourceManager.GetString("ToolbarPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除图像 的本地化字符串。
        /// </summary>
        internal static string ToolbarPrintPreviewDeleteImage {
            get {
                return ResourceManager.GetString("ToolbarPrintPreviewDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM Print 的本地化字符串。
        /// </summary>
        internal static string TooltipDicomPrint {
            get {
                return ResourceManager.GetString("TooltipDicomPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印排版 的本地化字符串。
        /// </summary>
        internal static string TooltipDicomPrintPreview {
            get {
                return ResourceManager.GetString("TooltipDicomPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        internal static string TooltipPan {
            get {
                return ResourceManager.GetString("TooltipPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除图像 的本地化字符串。
        /// </summary>
        internal static string TooltipPrintPreviewDeleteImage {
            get {
                return ResourceManager.GetString("TooltipPrintPreviewDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堆积 的本地化字符串。
        /// </summary>
        internal static string TooltipStack {
            get {
                return ResourceManager.GetString("TooltipStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The AE Title contains invalid characters. 的本地化字符串。
        /// </summary>
        internal static string ValidationAETitleInvalidCharacters {
            get {
                return ResourceManager.GetString("ValidationAETitleInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The AE Title must be between 1 and 16 characters. 的本地化字符串。
        /// </summary>
        internal static string ValidationAETitleLengthIncorrect {
            get {
                return ResourceManager.GetString("ValidationAETitleLengthIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Port must be between 1 and 65535. 的本地化字符串。
        /// </summary>
        internal static string ValidationPortOutOfRange {
            get {
                return ResourceManager.GetString("ValidationPortOutOfRange", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
